
/* MAIN */

const ERROR_CODE_INVALID_REQUEST = -1;
const ERROR_MESS_INVALID_REQUEST = 'Invalid request';

const ERROR_CODE_INVALID_VERSION = -2;
const ERROR_MESS_INVALID_VERSION = 'Invalid version';

const ERROR_CODE_UNSUPPORTED_VERSION = -3;
const ERROR_MESS_UNSUPPORTED_VERSION = 'Unsupported version';

const ERROR_CODE_INVALID_ID = -4;
const ERROR_MESS_INVALID_ID = 'Invalid id';

const ERROR_CODE_INVALID_PROCEDURE_NAME = -5;
const ERROR_MESS_INVALID_PROCEDURE_NAME = 'Invalid method';

const ERROR_CODE_INVALID_PROCEDURE_PARAMS = -6;
const ERROR_MESS_INVALID_PROCEDURE_PARAMS = 'Invalid params';

const ERROR_CODE_INVALID_CONTEXT = -7;
const ERROR_MESS_INVALID_CONTEXT = 'Invalid context';

const ERROR_CODE_FAILED_PROCEDURE_EXEC = -8;
const ERROR_MESS_FAILED_PROCEDURE_EXEC = 'Failed execution';

const FALLBACK_RESPONSE_ID = '';

const VERSION = '1.0.0';

/* EXPORT */

export {ERROR_CODE_INVALID_REQUEST, ERROR_MESS_INVALID_REQUEST};
export {ERROR_CODE_INVALID_VERSION, ERROR_MESS_INVALID_VERSION};
export {ERROR_CODE_UNSUPPORTED_VERSION, ERROR_MESS_UNSUPPORTED_VERSION};
export {ERROR_CODE_INVALID_ID, ERROR_MESS_INVALID_ID};
export {ERROR_CODE_INVALID_PROCEDURE_NAME, ERROR_MESS_INVALID_PROCEDURE_NAME};
export {ERROR_CODE_INVALID_PROCEDURE_PARAMS, ERROR_MESS_INVALID_PROCEDURE_PARAMS};
export {ERROR_CODE_INVALID_CONTEXT, ERROR_MESS_INVALID_CONTEXT};
export {ERROR_CODE_FAILED_PROCEDURE_EXEC, ERROR_MESS_FAILED_PROCEDURE_EXEC};
export {FALLBACK_RESPONSE_ID};
export {VERSION};
